<?php $product = $this->getProduct(); 
    // echo"<pre>";
    // print_r($product);

?>

<?php if($product->isEmpty()): ?>
    <h1>Product Not Found </h1>
<?php else:  ?>

<div class="product-view-container">
    <div class="product-main-section">
        <!-- Left Column -->
        <?php echo $this->getChildHtml('media'); ?>

        <!-- Right Column -->
        <div class="product-info-wrapper">
            <?php echo $this->getChildHtml('info'); ?>
            <?php echo $this->getChildHtml('actions'); ?>
            <?php echo $this->getChildHtml('specs'); ?>
        </div>
    </div>

    <!-- Long Description Section -->
    <?php echo $this->getChildHtml('description'); ?>
</div>
<?php endif; ?>